version: '3.9'

services:
  swansong.api:
    image: ${DOCKER_REGISTRY-}swansongapi
    build:
      context: .
      dockerfile: SwanSong.Api/Dockerfile
    depends_on:
        - sqldb
  sqldb:   
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server-2022-2
    environment:
        - MSSQL_SA_PASSWORD=Rcu9OP443mc#3xx
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025